name: Indiesoul
title: indiesoul's Repo | A blog theme for Jekyll
description: indiesoul's Data Analysis Repo 
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: indiesoul2@gmail.com
disqus_username: sizipusx2@gmail.com
show_hero: true
